### PR TITLE
pyFRF-1 BUG: Hann and Hamming window are the same, add more windows (…

### PR DESCRIPTION
**Pull request by jankoslavic**
…'Bartlett', 'Blackman', 'Kaiser')

### CODE REVIEW

**Comment by fbatista72** [comment]
Congratulations for your work.
I think the windows do not work.
The Python windows are set from 0 to T. Does pyfrf need T / 2 to T?
In your example, pyfrf does not work well with df = 0.5.
The Kaiser window needs a Beta.
Thank you.

**Comment by jankoslavic** [comment]
Dear @fbatista72 can you be more specific with your comment?

**Comment by fbatista72** [comment]
Dear Janko

I was not quite sure how the windows were applied.
But I've found it here: http://download.ni.com/evaluation/pxi/Understanding%20FFTs%20and%20Windowing.pdf
I've already clarified.

I found a Bug: The Kaiser window needs a Beta.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.kaiser.html 

To exterminate the noise of the imputs (exc and resp) are you thinking of implementing some filter?

Where can I find clear information on the calculation of H1 and H2?

Thank you

**Comment by jankoslavic** [comment]
Dear @fbatista72 indeed the beta parameter was not parsed. Please update to the latest version 0.37 where the parameter beta is parsed. See the Showcase to use windows (https://github.com/openmodal/pyFRF/blob/master/Showcase%20pyFRF.ipynb)

**Comment by fbatista72** [comment]
Dear Janko
In "Showcase pyFRF.ipynb" I think I have found a bug?
In [21]:
t = np.linspace(0, 1, num=l) -> t = np.linspace(0, 1/df, num=l)
In [22]:
ax2.set_xlim(left=0, right=1)  -> ax2.set_xlim(left=0, right=max(t)) 
Because the df can be different from 1.

**Comment by jankoslavic** [comment]
@fbatista72 I am sorry, but you got this wrong. `t` is an time array, going 
from 0 to 1 with `l` samples. 1 is not df.

**Comment by fbatista72** [comment]
Ok.
So what's wrong is the 
sampling_freq=1/t[1] -> sampling_freq=df/t[1]
You can experiment with several "df" values.

**Pull request merged**
